### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by Plutonian-9** [educelab/quick-segment#4]
create a _really basic_ walkthrough of the app and how to start using it

**Comment by Plutonian-9** [comment]
Currently, the video for the tutorial is too long to have a high-quality gif, change the long info page into navigatable single-point pages with short videos

**Comment by Plutonian-9** [comment]
GIFs need to be under 5 sec to have a readable quality. Needs further break up of steps. But here is a current demo.

https://user-images.githubusercontent.com/58576489/235958266-7b8e6de2-4ad7-45d9-bb45-43a60b6aab2d.mp4

**Comment by Plutonian-9** [comment]
Also only want the videos to start playing only when the tab is clicked on

**Comment by stephenrparsons** [comment]
This looks awesome, it had not even occurred to me to have this sort of thing inside the app.

**Comment by Plutonian-9** [comment]
Reopened to add better quality videos to the tutorial at a later time

**Comment by Plutonian-9** [comment]
changed longer QLabel gifs into QVideoWidget mp4s for higher-quality video resolution.

Pages with QVideoWidget now say in the terminal "failed to get textures for frame true", reason is currently unknown but it does not lead to any crash or break so ignoring it for now

**Comment by Plutonian-9** [comment]
New demo with mp4 replacements and addition of segmentation loading tab

https://user-images.githubusercontent.com/58576489/236117096-264e7c42-6972-4609-863d-0dab715a33ad.mp4
